#!/usr/bin/env bash
# script that automates nginx server to run at port 80
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/ 
service nginx start
