#!/usr/bin/env bash
#displays the content of the file /etc/passwd
#Your script should only display:
#    username
#    user id
#    Home directory path for the user
#Requirements:
#    You must use the while loop

while LISTFILE='' read -r LINE
do
	echo "$LINE" | cut -d ":" -f1,4,7
done < /etc/passwd
